import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Hero } from './shared/hero';
import { User } from './shared/user';
import { Client } from './shared/client';

@Injectable({providedIn: 'root'})
export class DataService implements InMemoryDbService {

  constructor() { }

  createDb(): {heroes: Hero [], users: User[], clients: Client[] } {
    return {
      heroes: [
        { id: 1, name: 'Boothstomper', team: 'avengers' },
        { id: 2, name: 'Drogfisher', team: 'avengers' },
        { id: 3, name: 'Bloodyllips', team: 'villains' },
        { id: 4, name: 'Mr Bu Moverse', team: 'villains' },
        { id: 5, name: 'Piranhaelli', team: 'avengers' }
      ],
      users: [{ name: 'hunter', pswd: 'hush' }],
      // tslint:disable block: max-line-length
      clients: [
        { id: 1, first_name: 'Adina', last_name: 'Turner', email: 'aturner0@bigcartel.com', gender: 'Bigender', ip_address: '239.119.220.226'},
        { id: 2, first_name: 'Stevy', last_name: 'Sobtka', email: 'ssobtka1@artisteer.com', gender: 'Genderqueer', ip_address: '86.48.87.129'},
        { id: 3, first_name: 'Thor', last_name: 'Thrush', email: 'tthrush2@independent.co.uk', gender: 'Non-binary', ip_address: '154.43.181.234'},
        { id: 4, first_name: 'Heda', last_name: 'Eskriet', email: 'heskriet3@gnu.org', gender: 'Male', ip_address: '141.177.27.44'},
        { id: 5, first_name: 'Garv', last_name: 'Olivera', email: 'golivera4@fotki.com', gender: 'Bigender', ip_address: '104.79.86.64'},
        { id: 6, first_name: 'Bryan', last_name: 'Groom', email: 'bgroom5@twitpic.com', gender: 'Agender', ip_address: '55.115.23.247'},
        { id: 7, first_name: 'Cornie', last_name: 'Balderson', email: 'cbalderson6@hao123.com', gender: 'Agender', ip_address: '182.159.146.7'},
        { id: 8, first_name: 'Allistir', last_name: 'Guisot', email: 'aguisot7@nytimes.com', gender: 'Non-binary', ip_address: '191.143.187.219'},
        { id: 9, first_name: 'Cesya', last_name: 'Winnard', email: 'cwinnard8@yellowbook.com', gender: 'Genderqueer', ip_address: '75.169.179.199'},
        { id: 10, first_name: 'Joell', last_name: 'McNeil', email: 'jmcneil9@shutterfly.com', gender: 'Bigender', ip_address: '231.141.25.56'},
        { id: 11, first_name: 'Portie', last_name: 'Grimster', email: 'pgrimstera@usnews.com', gender: 'Polygender', ip_address: '205.243.12.237'},
        { id: 12, first_name: 'Erik', last_name: 'Vidgeon', email: 'evidgeonb@jimdo.com', gender: 'Genderqueer', ip_address: '6.245.38.179'},
        { id: 13, first_name: 'Dulce', last_name: 'Lown', email: 'dlownc@instagram.com', gender: 'Polygender', ip_address: '9.233.0.124'},
        { id: 14, first_name: 'Amaleta', last_name: 'Antonazzi', email: 'aantonazzid@livejournal.com', gender: 'Polygender', ip_address: '117.110.4.111'},
        { id: 15, first_name: 'Meaghan', last_name: 'Dewhirst', email: 'mdewhirste@fastcompany.com', gender: 'Genderfluid', ip_address: '174.222.58.0'},
        { id: 16, first_name: 'Maggy', last_name: 'Padrick', email: 'mpadrickf@bizjournals.com', gender: 'Genderqueer', ip_address: '2.53.230.152'},
        { id: 17, first_name: 'Justina', last_name: 'Maile', email: 'jmaileg@pinterest.com', gender: 'Bigender', ip_address: '227.3.8.8'},
        { id: 18, first_name: 'Langsdon', last_name: 'Bowery', email: 'lboweryh@facebook.com', gender: 'Polygender', ip_address: '244.249.49.25'},
        { id: 19, first_name: 'Burnard', last_name: 'Jayume', email: 'bjayumei@loc.gov', gender: 'Genderqueer', ip_address: '126.239.200.148'},
        { id: 20, first_name: 'Chanda', last_name: 'Lafferty', email: 'claffertyj@purevolume.com', gender: 'Non-binary', ip_address: '29.96.253.253'},
        { id: 21, first_name: 'Rayner', last_name: 'Suggitt', email: 'rsuggittk@yale.edu', gender: 'Genderqueer', ip_address: '56.56.184.244'},
        { id: 22, first_name: 'Tiffani', last_name: 'Minchell', email: 'tminchelll@columbia.edu', gender: 'Genderfluid', ip_address: '66.167.212.155'},
        { id: 23, first_name: 'Burgess', last_name: 'Hembrow', email: 'bhembrowm@ucla.edu', gender: 'Agender', ip_address: '44.191.244.150'},
        { id: 24, first_name: 'Cathyleen', last_name: 'Chessor', email: 'cchessorn@livejournal.com', gender: 'Bigender', ip_address: '33.134.88.223'},
        { id: 25, first_name: 'Meryl', last_name: 'Maberley', email: 'mmaberleyo@umich.edu', gender: 'Non-binary', ip_address: '43.241.104.57'},
        { id: 26, first_name: 'Gay', last_name: 'MacCaughen', email: 'gmaccaughenp@psu.edu', gender: 'Male', ip_address: '42.97.197.206'},
        { id: 27, first_name: 'Raf', last_name: 'Lesley', email: 'rlesleyq@theglobeandmail.com', gender: 'Agender', ip_address: '86.105.138.202'},
        { id: 28, first_name: 'Tiebout', last_name: 'Brumen', email: 'tbrumenr@psu.edu', gender: 'Agender', ip_address: '230.41.100.182'},
        { id: 29, first_name: 'Raffarty', last_name: 'Witchell', email: 'rwitchells@yelp.com', gender: 'Female', ip_address: '250.142.164.236'},
        { id: 30, first_name: 'Hercules', last_name: 'Harner', email: 'hharnert@usgs.gov', gender: 'Male', ip_address: '207.43.220.165'},
        { id: 31, first_name: 'Merna', last_name: 'Franca', email: 'mfrancau@fotki.com', gender: 'Polygender', ip_address: '14.220.95.226'},
        { id: 32, first_name: 'Scarlet', last_name: 'Pine', email: 'spinev@theguardian.com', gender: 'Agender', ip_address: '46.91.226.146'},
        { id: 33, first_name: 'Jamison', last_name: 'Rumsey', email: 'jrumseyw@baidu.com', gender: 'Male', ip_address: '110.25.100.49'},
        { id: 34, first_name: 'Maximilien', last_name: 'Mapham', email: 'mmaphamx@hatena.ne.jp', gender: 'Female', ip_address: '213.201.192.211'},
        { id: 35, first_name: 'Hillary', last_name: 'Spellard', email: 'hspellardy@upenn.edu', gender: 'Genderfluid', ip_address: '182.126.162.245'},
        { id: 36, first_name: 'Brody', last_name: 'Hill', email: 'bhillz@ted.com', gender: 'Male', ip_address: '255.149.228.231'},
        { id: 37, first_name: 'Binny', last_name: 'Bachmann', email: 'bbachmann10@washington.edu', gender: 'Bigender', ip_address: '100.168.189.102'},
        { id: 38, first_name: 'Mal', last_name: 'Bydaway', email: 'mbydaway11@example.com', gender: 'Genderfluid', ip_address: '145.123.69.4'},
        { id: 39, first_name: 'Matthaeus', last_name: 'Warfield', email: 'mwarfield12@cdbaby.com', gender: 'Genderfluid', ip_address: '171.23.140.226'},
        { id: 40, first_name: 'Ad', last_name: 'Leathem', email: 'aleathem13@bloglines.com', gender: 'Male', ip_address: '151.32.145.195'},
        { id: 41, first_name: 'Valentine', last_name: 'Chatenet', email: 'vchatenet14@google.co.uk', gender: 'Male', ip_address: '119.142.134.233'},
        { id: 42, first_name: 'Idelle', last_name: 'Van Velde', email: 'ivanvelde15@posterous.com', gender: 'Bigender', ip_address: '88.218.10.176'},
        { id: 43, first_name: 'Mahmoud', last_name: 'Schoenrock', email: 'mschoenrock16@behance.net', gender: 'Non-binary', ip_address: '164.75.28.197'},
        { id: 44, first_name: 'Rinaldo', last_name: 'Boyat', email: 'rboyat17@latimes.com', gender: 'Male', ip_address: '106.166.32.24'},
        { id: 45, first_name: 'Mariellen', last_name: 'Flieger', email: 'mflieger18@narod.ru', gender: 'Agender', ip_address: '236.228.43.53'},
        { id: 46, first_name: 'Ardelia', last_name: 'Cuphus', email: 'acuphus19@live.com', gender: 'Polygender', ip_address: '126.217.148.67'},
        { id: 47, first_name: 'Tera', last_name: 'Collinwood', email: 'tcollinwood1a@cam.ac.uk', gender: 'Polygender', ip_address: '110.90.105.46'},
        { id: 48, first_name: 'Kassey', last_name: 'Terris', email: 'kterris1b@example.com', gender: 'Non-binary', ip_address: '150.189.255.223'},
        { id: 49, first_name: 'Dev', last_name: 'Wohlers', email: 'dwohlers1c@amazon.co.uk', gender: 'Non-binary', ip_address: '245.223.95.45'},
        { id: 50, first_name: 'Arthur', last_name: 'Inglis', email: 'ainglis1d@nbcnews.com', gender: 'Genderqueer', ip_address: '216.16.125.199'},
        { id: 51, first_name: 'Tabor', last_name: 'Markson', email: 'tmarkson1e@oakley.com', gender: 'Agender', ip_address: '20.26.47.10'},
        { id: 52, first_name: 'Andre', last_name: 'Matuszkiewicz', email: 'amatuszkiewicz1f@theglobeandmail.com', gender: 'Bigender', ip_address: '226.22.204.108'},
        { id: 53, first_name: 'Kipper', last_name: 'Baudy', email: 'kbaudy1g@ezinearticles.com', gender: 'Female', ip_address: '181.221.72.147'},
        { id: 54, first_name: 'Kellina', last_name: 'Tucknott', email: 'ktucknott1h@usgs.gov', gender: 'Genderfluid', ip_address: '37.67.175.142'},
        { id: 55, first_name: 'Ajay', last_name: 'Coggeshall', email: 'acoggeshall1i@bbc.co.uk', gender: 'Genderqueer', ip_address: '27.52.25.126'},
        { id: 56, first_name: 'Clayson', last_name: 'Weinham', email: 'cweinham1j@unc.edu', gender: 'Non-binary', ip_address: '189.117.11.214'},
        { id: 57, first_name: 'Cozmo', last_name: 'Rosini', email: 'crosini1k@senate.gov', gender: 'Agender', ip_address: '29.101.104.64'},
        { id: 58, first_name: 'Giraldo', last_name: 'Gisborne', email: 'ggisborne1l@telegraph.co.uk', gender: 'Male', ip_address: '55.209.169.134'},
        { id: 59, first_name: 'Margalo', last_name: 'Armatys', email: 'marmatys1m@npr.org', gender: 'Male', ip_address: '81.205.12.172'},
        { id: 60, first_name: 'Adelice', last_name: 'Rickesies', email: 'arickesies1n@toplist.cz', gender: 'Genderqueer', ip_address: '92.17.251.186'},
        { id: 61, first_name: 'Ezra', last_name: 'Hayley', email: 'ehayley1o@com.com', gender: 'Non-binary', ip_address: '19.183.62.234'},
        { id: 62, first_name: 'Hayward', last_name: 'Shepherd', email: 'hshepherd1p@diigo.com', gender: 'Bigender', ip_address: '152.35.77.42'},
        { id: 63, first_name: 'Wiatt', last_name: 'Hanley', email: 'wohanley1q@mlb.com', gender: 'Genderqueer', ip_address: '63.224.114.212'},
        { id: 64, first_name: 'Rodrigo', last_name: 'Jouning', email: 'rjouning1r@google.com.au', gender: 'Genderqueer', ip_address: '243.161.152.245'},
        { id: 65, first_name: 'Kerry', last_name: 'Dmitrievski', email: 'kdmitrievski1s@admin.ch', gender: 'Bigender', ip_address: '120.217.74.146'},
        { id: 66, first_name: 'Berton', last_name: 'Flinders', email: 'bflinders1t@edublogs.org', gender: 'Genderqueer', ip_address: '213.237.243.172'},
        { id: 67, first_name: 'Marnie', last_name: 'Volker', email: 'mvolker1u@ovh.net', gender: 'Polygender', ip_address: '180.159.71.246'},
        { id: 68, first_name: 'Phillis', last_name: 'De Gregario', email: 'pdegregario1v@weather.com', gender: 'Agender', ip_address: '4.152.190.96'},
        { id: 69, first_name: 'Shane', last_name: 'Piddington', email: 'spiddington1w@ifeng.com', gender: 'Non-binary', ip_address: '162.187.196.216'},
        { id: 70, first_name: 'Etti', last_name: 'Syratt', email: 'esyratt1x@ning.com', gender: 'Non-binary', ip_address: '180.207.135.20'},
        { id: 71, first_name: 'Cinda', last_name: 'Aldine', email: 'caldine1y@ca.gov', gender: 'Polygender', ip_address: '121.169.52.218'},
        { id: 72, first_name: 'Ravid', last_name: 'Cullingworth', email: 'rcullingworth1z@prnewswire.com', gender: 'Non-binary', ip_address: '162.245.160.41'},
        { id: 73, first_name: 'Brnaba', last_name: 'Purkess', email: 'bpurkess20@cbsnews.com', gender: 'Female', ip_address: '122.223.151.96'},
        { id: 74, first_name: 'Salli', last_name: 'Learmond', email: 'slearmond21@addtoany.com', gender: 'Genderfluid', ip_address: '199.185.71.134'},
        { id: 75, first_name: 'Walker', last_name: 'Grishanin', email: 'wgrishanin22@ucla.edu', gender: 'Genderfluid', ip_address: '159.139.25.32'},
        { id: 76, first_name: 'Chrissie', last_name: 'Ashment', email: 'cashment23@irs.gov', gender: 'Genderqueer', ip_address: '146.52.96.250'},
        { id: 77, first_name: 'Ad', last_name: 'Bather', email: 'abather24@ebay.co.uk', gender: 'Male', ip_address: '58.93.10.75'},
        { id: 78, first_name: 'Hestia', last_name: 'Leys', email: 'hleys25@quantcast.com', gender: 'Female', ip_address: '159.67.23.181'},
        { id: 79, first_name: 'Hewe', last_name: 'Ioannidis', email: 'hioannidis26@cbc.ca', gender: 'Genderqueer', ip_address: '14.3.156.144'},
        { id: 80, first_name: 'Berty', last_name: 'Flaherty', email: 'bflaherty27@cloudflare.com', gender: 'Genderfluid', ip_address: '143.91.101.253'},
        { id: 81, first_name: 'Langston', last_name: 'Farguhar', email: 'lfarguhar28@go.com', gender: 'Male', ip_address: '92.224.227.78'},
        { id: 82, first_name: 'Dilan', last_name: 'Hankinson', email: 'dhankinson29@arizona.edu', gender: 'Genderqueer', ip_address: '146.164.123.79'},
        { id: 83, first_name: 'Wilden', last_name: 'Dadswell', email: 'wdadswell2a@dailymail.co.uk', gender: 'Female', ip_address: '247.134.126.65'},
        { id: 84, first_name: 'Derrek', last_name: 'L\'Archer', email: 'dlarcher2b@disqus.com', gender: 'Bigender', ip_address: '110.94.214.49'},
        { id: 85, first_name: 'Alica', last_name: 'Vanyatin', email: 'avanyatin2c@seesaa.net', gender: 'Female', ip_address: '2.170.46.212'},
        { id: 86, first_name: 'Melania', last_name: 'Korfmann', email: 'mkorfmann2d@archive.org', gender: 'Bigender', ip_address: '46.222.229.19'},
        { id: 87, first_name: 'Brandy', last_name: 'Cretney', email: 'bcretney2e@yellowpages.com', gender: 'Bigender', ip_address: '74.101.214.95'},
        { id: 88, first_name: 'Geoffrey', last_name: 'Spini', email: 'gspini2f@smugmug.com', gender: 'Genderqueer', ip_address: '194.52.187.230'},
        { id: 89, first_name: 'Trixy', last_name: 'MacKeller', email: 'tmackeller2g@yellowpages.com', gender: 'Non-binary', ip_address: '106.110.224.60'},
        { id: 90, first_name: 'Shirlene', last_name: 'Retallick', email: 'sretallick2h@bluehost.com', gender: 'Non-binary', ip_address: '148.252.152.38'},
        { id: 91, first_name: 'Doralynn', last_name: 'Meese', email: 'dmeese2i@senate.gov', gender: 'Genderfluid', ip_address: '156.192.54.196'},
        { id: 92, first_name: 'Walden', last_name: 'Steggals', email: 'wsteggals2j@huffingtonpost.com', gender: 'Genderqueer', ip_address: '145.92.131.121'},
        { id: 93, first_name: 'Maryl', last_name: 'Leonards', email: 'mleonards2k@blinklist.com', gender: 'Female', ip_address: '247.214.128.204'},
        { id: 94, first_name: 'Rustie', last_name: 'Bartaletti', email: 'rbartaletti2l@fotki.com', gender: 'Agender', ip_address: '243.116.246.203'},
        { id: 95, first_name: 'Dar', last_name: 'Pirazzi', email: 'dpirazzi2m@list-manage.com', gender: 'Agender', ip_address: '48.213.171.237'},
        { id: 96, first_name: 'Wally', last_name: 'Roscrigg', email: 'wroscrigg2n@usda.gov', gender: 'Agender', ip_address: '89.110.238.95'},
        { id: 97, first_name: 'Janenna', last_name: 'Gall', email: 'jgall2o@java.com', gender: 'Bigender', ip_address: '232.29.61.95'},
        { id: 98, first_name: 'Mathias', last_name: 'Hanscomb', email: 'mhanscomb2p@vistaprint.com', gender: 'Male', ip_address: '243.42.135.155'},
        { id: 99, first_name: 'Gaston', last_name: 'Westrey', email: 'gwestrey2q@aol.com', gender: 'Non-binary', ip_address: '27.238.13.80'},
        { id: 100, first_name: 'Laurent', last_name: 'Stetlye', email: 'lstetlye2r@discovery.com', gender: 'Female', ip_address: '139.158.24.88'}]
    };
  }
}
